services:
  mosquitto:
    build: https://github.com/MicroWebStacks/copper.git#main:mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./cache/log/mosquitto:/mosquitto/log
  fetcher:
    build: https://github.com/MicroWebStacks/copper.git#main:fetcher
    volumes:
      - ./cache/fetch:/fetch
    depends_on:
      - mosquitto
  markdown:
    build: https://github.com/MicroWebStacks/applications-services.git#main:markdown
    volumes:
      - ./cache/fetch:/fetch
      - ./cache/process:/process
      - ./cache/web:/web
    depends_on:
      - mosquitto
  runner:
    build: https://github.com/MicroWebStacks/copper.git#main:runner
    volumes:
      - ./workflow.yaml:/app/workflow.yaml
    depends_on:
      - fetcher
      - markdown
